### ISSUE TITLE
Contribute to this repo...

### ISSUE THREAD

**Issue by AIdevol** [AIdevol/Leetcode_tasks#1]
Notes:- 1. need to separate langauge code from leetcode.

2. Make separate file for each language and put your code as followed by python file in the repo.

3. Make clean repo And do not colonised them.

**Comment by Himanshi-Saini-0277** [comment]
hi i want to update your code '

My Proposal is i will manage your code and do it according to your niche.

**Comment by AIdevol** [comment]
Can you elaborate on your approach in detail?

**Comment by AIdevol** [comment]
Add your solution.
